
version: '3'
services:

  engine:
    build: ./engine
    container_name: engine
    tty: true
    privileged: true
    volumes:
      - ./engine/engine.py:/engine.py
    command: ["python", "/engine.py"]
    restart: on-failure

